#!/usr/bin/env ruby

CONFIG_PATH = File.expand_path("~/.Xdefaults")
DELIM = "!XDEFAULTS-THEME"

original = File.read(CONFIG_PATH)

FILES = Dir["Xdefaults/*"]
FILES.delete_if { |file| File.basename(file) !~ /^#{ARGV.first}/ } if ARGV.first
THEMES = FILES.map { |f| File.read(f) }

THEMES.each do |theme|
  head, colors, tail = original.split(/#{DELIM}\n?/)
  result = [head, theme, tail].join("#{DELIM}\n")
  File.open(CONFIG_PATH, "w") { |f| f << result }

  system("xrdb #{CONFIG_PATH}; urxvt")
  system("termcolors")
  puts(theme.split("\n").first)
  print("Choose this one? [Y/N/Q]: ")
  $input = STDIN.gets()
  break if $input =~ /y|q/i
end

if $input !~ /y/i
  File.open(CONFIG_PATH, "w") { |f| f << original }
  system("xrdb #{CONFIG_PATH}")
end
